image: docker
services:
  - docker:dind
stages:
  - deploy
variables:
  DOCKER_DRIVER: overlay2
  KUBE_CONFIG_FILE: /etc/deploy/config
  DOCKER_IMAGE: aabishkar/node:$CI_COMMIT_SHORT_SHA
deploy:
  stage: deploy
  script:
    - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - mkdir -p /etc/deploy # Create a folder for config file
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBE_CONFIG_FILE} # Write kubernetes config in config file
    - apk add --update --no-cache curl git # Install dependencies
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl # Download kubectl binary
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - docker build --no-cache -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - sed -i 's+imageName+${DOCKER_IMAGE}+' k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml --kubeconfig=/etc/deploy/config # kubernetes apply
