apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    sha256: {} # use git commit policy
  artifacts:
    - image: aabishkar/node-demo
      context: .
      sync:
        manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: "src/**/*.js"
            dest: .
